services:
  devhabit.api:
    image: ${DOCKER_REGISTRY-}devhabitapi
    container_name: devhabit.api
    build:
      context: .
      dockerfile: DevHabit.Api/Dockerfile
    ports:
      - 9000:8080
      - 9001:8081
    volumes:
      - ./.certificates:/https:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=devpassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://devhabit.aspire-dashboard:18889
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
  devhabit.postgres:
    image: postgres:17.2 
    container_name: devhabit.postgres
    environment:
      - POSTGRES_DB=devhabit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/postgres_data:/var/lib/postgresql/data
    ports:
      - 5492:5432

  devhabit.aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    container_name: devhabit.aspire-dashboard
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    ports:
      - 18888:18888